project:
  type: website
  output-dir: docs
  preview: 
    port: 4200
    
    
    
website:
  sidebar:
    logo: "https://www.hi.is/sites/default/files/styles/vi_hengi_-_tenglar/public/ame18/hilogo.png?itok=9UgaDOcd"
    tools: 
      - icon: github
        menu:
          - text: Tilkynna villu
            url: https://github.com/bgautijonsson/rfragrunni/issues
          - text: Kóði
            url: https://github.com/bgautijonsson/rfragrunni
    contents:
      - text: "Heim"
        file: index.qmd
      - section: "R frá grunni"
        contents:
          - rfyrirbyrjendur/kafli1/index.qmd
          - rfyrirbyrjendur/kafli2/index.qmd
          - rfyrirbyrjendur/kafli3/index.qmd
          - rfyrirbyrjendur/kafli4/index.qmd
          - rfyrirbyrjendur/kafli5/index.qmd
          - rfyrirbyrjendur/kafli6/index.qmd
          - rfyrirbyrjendur/kafli7/index.qmd
          - rfyrirbyrjendur/kafli8/index.qmd
          - rfyrirbyrjendur/kafli9/index.qmd
          - rfyrirbyrjendur/kafli10/index.qmd
          - rfyrirbyrjendur/kafli11/index.qmd

format: 
  html:
    theme: [flatly, theme.scss]
    execute:
      freeze: auto
      warning: false
      message: false
webr:
  channel-type: "post-message"
filters: 
  - webr
title-block-banner: false

editor: source

author: 
  - name: Anna Helga Jónsdóttir
    email: ahj@hi.is
    affiliation: Háskóli Íslands
  - name: Sigrún Helga Lund
    email: sigrunhl@hi.is
    affiliation: Háskóli Íslands
  - name: Bjarki Þór Elvarsson
    email: bjarki.elvarsson@hafogvatn.is
    affiliation: Hafrannsóknarstofnun
  - name: Brynjólfur Gauti Guðrúnar Jónsson
    email: brynjolfur@hi.is
    affiliation: Háskóli Íslands
    
    
    
    
language:
  title-block-author-single: "Höfundur"
  title-block-author-plural: "Höfundar"
  title-block-affiliation-single: "Stofnun"
  title-block-affiliation-plural: "Stofnun"
  title-block-published: "Síðast uppfært"