---
title: "Líkindafræðileg undirstaða"
webr:
  packages: ['ggplot2', 'patchwork']
---

# Líkindadreifingar

## Strjálar dreifingar

Í þessum hluta munum við kynnast aðferðum sem tengjast strjálum líkindadreifingum. Föllin sem byrja á `d` gefa okkur massafallið (e. probability mass function) en föllin sem byrja á `p` gefa okkur dreififallið (e. probability distribution funciton).

### Tvíkosta dreifing

```{webr-r}
#| context: setup

teikna_tvikosta <- function(k, n, p) {
  
  if (k > n) {
    return("k getur aldrei verið stærri en n (getur ekki kastað krónu 10 sinnum og fengið 15 þorska)")
  }
  
  x <- seq(0, n)
  y1 <- dbinom(x, size = n, prob = p)
  keep <- y1 > 1e-5
  y1 <- y1[keep]
  x <- x[keep]
  
  y2 <- pbinom(x, size = n, prob = p)
  
  p1 <- ggplot() +
    geom_col(aes(x = x, y = y1, fill = (x == k)), show.legend = FALSE) +
    scale_fill_brewer(palette = "Greys") +
    theme_classic() +
    theme(
      axis.text.y = element_blank(),
      axis.ticks.y = element_blank(),
      axis.line.y = element_blank(),
      axis.title.y = element_blank()
    ) +
    coord_cartesian(expand = FALSE) +
    labs(
      title = "Notkun á dbinom(k, n, p)",
      subtitle = "Líkurnar á að X sé jafnt og k",
      x = "X"
    )
  
  
  p2 <- ggplot() +
    geom_col(aes(x = x, y = y2, fill = (x <= k)), show.legend = FALSE) +
    scale_fill_brewer(palette = "Greys") +
    theme_classic() +
    theme(
      axis.text.y = element_blank(),
      axis.ticks.y = element_blank(),
      axis.line.y = element_blank(),
      axis.title.y = element_blank()
    ) +
    coord_cartesian(expand = FALSE) +
    labs(
      title = "notkun á pbinom(k, n, p)",
      subtitle = "Líkurnar á að X sé minna eða jafnt og k",
      x = "X"
    )
  
  p1 + p2 +
    plot_annotation(
      title = "Samanburður á hvernig við notum dbinom() og pbinom()"
    )
}
```

Hér munum við kynnast aðferðunum `dbinom()` og `pbinom()`. Keyrðu kóðann að neðan til að sjá dæmi um tvíkostadreifingu. Lestu svo um `dbinom()` og `pbinom()` og athugaðu svo hvort þú skiljir hvað er að gerast á bak við tjöldin þegar þú prófar að breyta tölunum k, n og p til að fá mismunandi útgáfur af myndinni.

```{webr-r}
k <- 40
n <- 100
p <- 0.3

teikna_tvikosta(k, n, p)
```


#### dbinom()

::: {.callout-note}
## Athugið

**Inntak:** útkoma úr tvíkostadreifingu, stikar tvíkostadreifingarunnar  

**Úttak:** líkur á útkomunni
:::

`dbinom()` aðferðin reiknar líkur á forminu þar sem X er slembistærð sem fylgir tvíkostadreifingunni. Við þurfum að mata aðferðina með þremur tölum, k, n og p þar sem k er fjöldi heppnaðra tilrauna, n er fjöldi tilrauna og p eru líkurnar á jákvæðri útkomu í hverri tilraun fyrir sig:

::: {.callout-tip}
## Æfing

Hverjar eru líkurnar á að fá tvo þorska þegar krónu er kastað upp fjórum sinnum? Settu réttar tölur inn fyrir k, n og p.

```{webr-r}
dbinom(k, n, p)
```
:::  

### pbinom

::: {.callout-note}
## Athugið

**Inntak:** útkoma úr tvíkostadreifingu, stikar tvíkostadreifingarinnar  

**Úttak:** líkur
:::

`pbinom()` aðferðin reiknar líkur á forminu þar sem X er slembistærð sem fylgir tvíkostadreifingunni. Við þurfum að mata aðferðina með þremur tölum, k, n og p þar sem k er fjöldi heppnaðra tilrauna, n er fjöldi tilrauna og p eru líkurnar á jákvæðri útkomu í hverri tilraun fyrir sig:

::: {.callout-tip}
## Æfing

Hverjar eru líkurnar á að sjá 3 eða færri þorska þegar krónu er kastað upp 9 sinnum? Settu réttar tölur inn fyrir k, n og p.

```{webr-r}
pbinom(k, n, p)
```
:::  

### Posson dreifing

```{webr-r}
#| context: setup

teikna_poisson <- function(k, lambda) {
  
  x <- seq(0, pmax(qpois(0.999999, lambda), k))
  y1 <- dpois(x, lambda = lambda)
  keep <- y1 > 1e-5
  y1 <- y1[keep]
  x <- x[keep]
  
  y2 <- ppois(x, lambda = lambda)
  
  p1 <- ggplot() +
    geom_col(aes(x = x, y = y1, fill = (x == k)), show.legend = FALSE) +
    scale_x_continuous(
      breaks = unique(floor(pretty(x)))
    ) +
    scale_fill_brewer(palette = "Greys") +
    theme_classic() +
    theme(
      axis.text.y = element_blank(),
      axis.ticks.y = element_blank(),
      axis.line.y = element_blank(),
      axis.title.y = element_blank()
    ) +
    coord_cartesian(expand = FALSE) +
    labs(
      title = "Notkun á dpois(k, n, p)",
      subtitle = "Líkurnar á að X sé jafnt og k",
      x = "X"
    )
  
  
  p2 <- ggplot() +
    geom_col(aes(x = x, y = y2, fill = (x <= k)), show.legend = FALSE) +
    scale_x_continuous(
      breaks = unique(floor(pretty(x)))
    ) +
    scale_fill_brewer(palette = "Greys") +
    theme_classic() +
    theme(
      axis.text.y = element_blank(),
      axis.ticks.y = element_blank(),
      axis.line.y = element_blank(),
      axis.title.y = element_blank()
    ) +
    coord_cartesian(expand = FALSE) +
    labs(
      title = "notkun á ppois(k, n, p)",
      subtitle = "Líkurnar á að X sé minna eða jafnt og k",
      x = "X"
    )
  
  p1 + p2 +
    plot_annotation(
      title = "Samanburður á hvernig við notum dpois() og ppois()"
    )
}
```

```{webr-r}
k <- 7
lambda <- 4

teikna_poisson(k, lambda)
```

#### dpois()

::: {.callout-note}
## Athugið

**Inntak:** útkoma úr Poisson dreifingu, stiki Poisson dreifingarinnar  

**Úttak:** líkur
:::

`dpois()` aðferðin reiknar líkur á forminu þar sem X er slembistærð sem fylgir Poisson dreifingunni. Við þurfum að mata aðferðina með tveimur tölum, k og $\lambda$ þar sem k er fjöldi heppnaðra tilrauna og $\lambda$ er væntigildi slembistærðarinnar X:

::: {.callout-tip}
## Æfing

Hverjar eru líkurnar á að 3 kúnnar komi á kassann í Krónunni á einni mínútu, þar sem meðalfjöldi kúnna á mínútu er 1.5? Settu réttar tölur inn fyrir k og $\lambda$

```{webr-r}
dpois(k, lambda)
```
:::  

#### ppois()

::: {.callout-note}
## Athugið

**Inntak:** útkoma úr Poisson dreifingu, stikar Poisson dreifingarinnar  

**Úttak:** líkur
:::

`ppois()` aðferðin reiknar líkur á forminu $P(X < k)$ þar sem X er slembistærð sem fylgir Poisson dreifingunni. Við þurfum að mata aðferðina með tveimur tölum, k og $\lambda$ þar sem k er fjöldi heppnaðra tilrauna og $\lambda$ er væntigildi slembistærðarinnar X.

::: {.callout-tip}
## Æfing

Hverjar eru líkurnar á að 10 eða færri bílar keyra framhjá leikskóla á einni klukkustund þegar meðalfjöldu bíla á klukkustund er 7? Settu réttar tölur inn fyrir k og $\lambda$

```{webr-r}
ppois(k, lambda)
```
:::  


## Samfelldar dreifingar



### Normaldreifing

### Veldisvísisdreifing

### Gammadreifing

### Betadreifing


